import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { CategoryIcon, SurfaceCard } from "@/components/finance-ui";
import { ScreenContainer } from "@/components/screen-container";
import { financeUi } from "@/constants/finance-ui";
import { useColors } from "@/hooks/use-colors";
import { calculateBudgetProgress, formatMoney, getCategoryBudget, getCurrencySymbol, getMonthTransactions, parseAmountToCents, toAmountInput } from "@/lib/finance";
import { useFinance } from "@/lib/finance-store";

export default function CategoryBudgetEditorScreen() {
  const { id, monthKey } = useLocalSearchParams<{ id: string; monthKey: string }>();
  const colors = useColors();
  const { categories, transactions, categoryBudgets, preferences, setCategoryBudget, deleteCategoryBudget } = useFinance();
  const category = categories.find((item) => item.id === id && item.type === "expense");
  const target = useMemo(() => category ? getCategoryBudget(categoryBudgets, monthKey, category.id) : undefined, [category, categoryBudgets, monthKey]);
  const spent = useMemo(() => category ? getMonthTransactions(transactions, new Date(`${monthKey}-01T12:00:00`)).filter((transaction) => transaction.categoryId === category.id && transaction.type === "expense").reduce((sum, transaction) => sum + transaction.amountCents, 0) : 0, [category, monthKey, transactions]);
  const [amount, setAmount] = useState("");
  const [isSaving, setIsSaving] = useState(false);
  useEffect(() => { setAmount(target ? toAmountInput(target.amountCents) : ""); }, [target]);
  useEffect(() => { if (!category) router.back(); }, [category]);
  if (!category) return null;
  const progress = calculateBudgetProgress(spent, target?.amountCents ?? 0);
  const save = async () => { const cents = parseAmountToCents(amount); if (cents <= 0) { Alert.alert("Add a category target", "Enter an amount greater than zero."); return; } setIsSaving(true); const didSave = await setCategoryBudget(monthKey, category.id, cents); setIsSaving(false); if (didSave) router.back(); else Alert.alert("Couldn’t save target", "Please try again."); };
  const remove = () => { Alert.alert("Remove category target?", "Your category spending stays recorded.", [{ text: "Cancel", style: "cancel" }, { text: "Remove", style: "destructive", onPress: () => { void deleteCategoryBudget(monthKey, category.id).then((didDelete) => { if (didDelete) router.back(); else Alert.alert("Couldn’t remove target", "Please try again."); }); } }]); };
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><View style={styles.content}><View style={styles.header}><Pressable accessibilityRole="button" accessibilityLabel="Close category target" onPress={() => router.back()} style={({ pressed }) => [styles.closeButton, { backgroundColor: colors.surface, borderColor: colors.border }, pressed && styles.pressed]}><MaterialIcons name="close" size={22} color={colors.foreground} /></Pressable><Text style={[styles.title, { color: colors.foreground }]}>Category target</Text><View style={styles.closeButton} /></View><SurfaceCard><View style={styles.categoryHeader}><CategoryIcon category={category} size={44} /><View><Text style={[styles.categoryName, { color: colors.foreground }]}>{category.name}</Text><Text style={[styles.month, { color: colors.muted }]}>{monthKey}</Text></View></View><Text style={[styles.spentLabel, { color: colors.muted }]}>SPENT THIS MONTH</Text><Text style={[styles.spentValue, { color: progress.isAtBudget ? colors.error : colors.foreground }]}>{formatMoney(spent, preferences.currencyCode)}</Text>{target ? <Text style={[styles.remaining, { color: progress.isAtBudget ? colors.error : colors.muted }]}>{progress.isOverBudget ? `${formatMoney(Math.abs(progress.remainingCents), preferences.currencyCode)} over target` : `${formatMoney(progress.remainingCents, preferences.currencyCode)} remaining`}</Text> : null}</SurfaceCard><Text style={[styles.sectionLabel, { color: colors.muted }]}>MONTHLY CATEGORY LIMIT</Text><SurfaceCard><View style={[styles.amountRow, { backgroundColor: colors.background, borderColor: colors.border }]}><Text style={[styles.currencySymbol, { color: colors.primary }]}>{getCurrencySymbol(preferences.currencyCode)}</Text><TextInput value={amount} onChangeText={setAmount} placeholder="0.00" placeholderTextColor={colors.muted} keyboardType="decimal-pad" maxLength={12} accessibilityLabel={`Monthly ${category.name} target in ${preferences.currencyCode}`} style={[styles.amountInput, { color: colors.foreground }]} returnKeyType="done" onSubmitEditing={save} /></View><Pressable accessibilityRole="button" accessibilityLabel="Save category target" disabled={isSaving} onPress={save} style={({ pressed }) => [styles.primaryButton, { backgroundColor: colors.primary }, isSaving && styles.disabled, pressed && styles.pressed]}><Text style={[styles.primaryButtonText, { color: colors.background }]}>{isSaving ? "Saving…" : "Save category target"}</Text></Pressable>{target ? <Pressable accessibilityRole="button" accessibilityLabel="Remove category target" onPress={remove} style={({ pressed }) => [styles.removeButton, pressed && styles.pressed]}><Text style={[styles.removeButtonText, { color: colors.error }]}>Remove target</Text></Pressable> : null}</SurfaceCard></View></ScreenContainer>;
}

const styles = StyleSheet.create({ amountInput: { flex: 1, height: "100%", padding: 0, fontSize: 30, lineHeight: 38, fontWeight: "800", fontVariant: ["tabular-nums"] }, amountRow: { height: 58, borderRadius: financeUi.radius.button, borderWidth: financeUi.line.subtle, paddingHorizontal: 14, flexDirection: "row", alignItems: "center" }, categoryHeader: { flexDirection: "row", alignItems: "center", gap: 12 }, categoryName: { fontSize: 17, lineHeight: 23, fontWeight: "800" }, closeButton: { width: financeUi.size.tapTarget, height: financeUi.size.tapTarget, borderRadius: 22, borderWidth: financeUi.line.subtle, alignItems: "center", justifyContent: "center" }, content: { flex: 1, padding: financeUi.spacing.page }, currencySymbol: { fontSize: 24, fontWeight: "800", marginRight: 5 }, disabled: { opacity: 0.65 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 22 }, month: { fontSize: 13, lineHeight: 19, marginTop: 1 }, pressed: { opacity: financeUi.opacity.pressed, transform: [{ scale: 0.98 }] }, primaryButton: { minHeight: 50, borderRadius: financeUi.radius.button, marginTop: 14, alignItems: "center", justifyContent: "center" }, primaryButtonText: { fontSize: 15, lineHeight: 21, fontWeight: "800" }, remaining: { fontSize: 14, lineHeight: 20, fontWeight: "700", marginTop: 1 }, removeButton: { minHeight: financeUi.size.tapTarget, alignSelf: "center", justifyContent: "center", marginTop: 8, paddingHorizontal: 12 }, removeButtonText: { fontSize: 14, lineHeight: 20, fontWeight: "800" }, sectionLabel: { fontSize: 11, lineHeight: 16, fontWeight: "800", letterSpacing: 1, marginTop: 25, marginBottom: 9 }, spentLabel: { fontSize: 11, lineHeight: 16, fontWeight: "800", letterSpacing: 0.9, marginTop: 24 }, spentValue: { fontSize: 30, lineHeight: 38, fontWeight: "800", fontVariant: ["tabular-nums"], marginTop: 2 }, title: { fontSize: 17, lineHeight: 23, fontWeight: "800" } });
